version: '3.8'

services:
  db:
    image: postgres:16.3
    container_name: google-scraper-web-db
    environment:
      - POSTGRES_DB=google_scraper_web_test
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432"

  redis:
    image: redis:7.0.9
    container_name: google-scraper-web-redis
    ports:
      - "6379"

  test:
    build:
      context: .
      cache_from:
        - ${DOCKER_REGISTRY_HOST}/${DOCKER_IMAGE}:${BRANCH_TAG}-test
      args:
        - BUILD_ENV=test
        - RUBY_ENV=test
        - NODE_ENV=test
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_IMAGE}:${BRANCH_TAG}-test
    container_name: google-scraper-web-test
    command: bin/test.sh
    stdin_open: true
    tty: true
    depends_on:
      - db
    volumes:
      - "ruby-bundle:/bundle"
      - "${PWD}/tmp/screenshots:/google_scraper_web/tmp/screenshots"
      - "${PWD}/coverage:/google_scraper_web/coverage"
      - "${PWD}/log:/google_scraper_web/log"
    environment:
      - RACK_ENV=test
      - RAILS_ENV=test
      - NODE_ENV=test
      - DB_HOST=db
      - CI=$CI
      - TEST_RETRY=$TEST_RETRY
      - PORT=$PORT
      - DANGER_GITHUB_API_TOKEN=$DANGER_GITHUB_API_TOKEN

volumes:
  ruby-bundle:
